FROM debian:10-slim 

RUN apt-get update && apt-get install -y \
    libpq5 ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /root/
COPY target/release/dino-park-packs .
CMD ["./dino-park-packs"]  