# This is used for local development only.

services:
  postgres:
    image: postgres:18.3
    ports:
    - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: dino-park-packs-test-local
      POSTGRES_PASSWORD: localhost

  adminer:
    image: adminer:5-standalone
    ports:
    - 127.0.0.1:9000:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  packs:
    image: dino-park-packs:development
    build:
      context: ../
      dockerfile: Dockerfile.local
    environment:
      DPP_SETTINGS: /root/.settings.json
    volumes:
    - ../dev/settings.json:/root/.settings.json
    ports:
    - 127.0.0.1:8085:8085
